/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.Collectors;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        List<Integer> list = Arrays.asList(1,2,3,4,5,6);

        list.stream().filter(i -> i%2 ==0).collect(Collectors.toList());

        System.out.println(new App().getGreeting());
    }
}
